# language : node_js 
# node_js : 
#   - "node"
# install : 
#   - npm install
#   - npm install -g yarn react-native-cli
# script : 
#   - npm test




language: android
install: 
  - npm install
android: #1.3
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-16
script: 
  - npm run ci #2
  - cd android && ./gradlew assembleRelease #3